name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"
          cache: "npm" # Enables npm caching

      # The local build and start steps aren't necessary since you're building on the server
      # You can remove the separate backend and frontend jobs

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: paluraandrei.tplinkdns.com
          username: paluras
          port: 5000
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Set Node.js version
            nvm use 22.2.0

            # Backend deploy
            echo "Deploying backend..."
            cd /var/www/adoptProject/backend || exit
            git pull origin master
            npm ci # Faster and more reliable than npm install
            npm run build
            pm2 restart adopt-backend || pm2 start npm --name "adopt-backend" -- run start

            # Frontend deploy
            echo "Deploying frontend..."
            cd /var/www/adoptProject/frontend/animal-adoption || exit
            git pull origin master
            npm ci
            npm run build

            echo "Deployment complete!"
