name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  # Build and test the backend
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start backend
        working-directory: ./backend
        run: nohup npm run start &

  # Build the frontend
  frontend:
    runs-on: ubuntu-latest
    needs: backend # Ensure the backend job finishes first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - name: Install frontend dependencies
        working-directory: ./frontend/animal-adoption
        run: npm install

      - name: Build frontend
        working-directory: ./frontend/animal-adoption
        run: npm run build

  # Deploy to Ubuntu server
  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend] # Ensure both backend and frontend are built

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Deployment Script
        run: |
          chmod +x deploy.sh
          ./deploy.sh
